version: "3"
services:
  #Database
  db:
    image: arangodb:3.6.13
    environment:
      - ARANGO_ROOT_PASSWORD=
    ports:
      - 8529:8529
    networks:
      - spring-cloud-network
    volumes:
      - ./dev/db:/var/lib/arangodb3
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8529" ]
#      interval: 5s
#      timeout: 10s
#      retries: 5

networks:
  spring-cloud-network:
    driver: bridge
